nginx_name: ingress-nginx
nginx_namespace: ingress-nginx
kubeconfig: "~/.kube/config"
chart_version: 3.20.1

loadBalancerSourceRanges: ["0.0.0.0/0"]

nginx_config:
  controller:
    service: 
      externalTrafficPolicy: Local
      sessionAffinity: None 
      loadBalancerSourceRanges: "{{ loadBalancerSourceRanges }}"
    config:
      use-forwarded-headers: "true"
    tcp: {}
    udp: {}
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 5; /usr/local/nginx/sbin/nginx -c /etc/nginx/nginx.conf -s quit; while pgrep -x nginx; do sleep 1; done"]
    terminationGracePeriodSeconds: 600

prviate_cluster:
  aws:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
  azure:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  gcp:
    controller:
      service: 
        annotations:
          networking.gke.io/load-balancer-type: "Internal"

PRIVATE_CLUSTER_ENABLE: false
