---
- name: create multi-tenant-job folder
  file:
    state: directory
    dest: "{{ DEPLOY_DIR }}/multi-tenant/sas-tenant-job"
    mode: "0770"
  when: V4_CFG_MULTITENANT_ENABLE
  tags:
    - install

- name: copy - sas-tenant-job
  copy:
    src: "{{ DEPLOY_DIR }}/sas-bases/examples/sas-tenant-job/"
    dest: "{{ DEPLOY_DIR }}/multi-tenant/sas-tenant-job"
    mode: "0770"
  when: V4_CFG_MULTITENANT_ENABLE
  tags:
    - install

- name: update namespace
  replace:
    path: "{{ item }}"
    regexp: "{% raw %}{{ VIYA-DEPLOYMENT-NAMESPACE }}{% endraw %}"
    replace: "{{ NAMESPACE }}"
  with_items:
    - "{{ DEPLOY_DIR }}/multi-tenant/sas-tenant-job/tenant-job-service-account-role.yaml"
    - "{{ DEPLOY_DIR }}/multi-tenant/sas-tenant-job/kustomization-onboard.yaml"
    - "{{ DEPLOY_DIR }}/multi-tenant/sas-tenant-job/kustomization-offboard.yaml"
  when: V4_CFG_MULTITENANT_ENABLE
  tags:
    - install

- name: sas-tenant-job - update sas-tenant-ids and sas-provider-password
  replace:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { path: '{{ DEPLOY_DIR }}/multi-tenant/sas-tenant-job/tenant-onboard-job.yaml', regexp: '{% raw %}{{ SAS-TENANT-IDS }}{% endraw %}', replace: '{{ SAS_TENANT_IDS }}' }
    - { path: '{{ DEPLOY_DIR }}/multi-tenant/sas-tenant-job/tenant-offboard-job.yaml', regexp: '{% raw %}{{ SAS-TENANT-IDS }}{% endraw %}', replace: '{{ SAS_TENANT_IDS }}' }
    - { path: '{{ DEPLOY_DIR }}/multi-tenant/sas-tenant-job/tenant-onboard-job.yaml', regexp: '{% raw %}{{ SAS-PROVIDER-PASSWORD }}{% endraw %}', replace: '{{ SAS_PROVIDER_PASSWORD }}'}
    - { path: '{{ DEPLOY_DIR }}/multi-tenant/sas-tenant-job/tenant-offboard-job.yaml', regexp: '{% raw %}{{ SAS-PROVIDER-PASSWORD }}{% endraw %}', replace: '{{ SAS_PROVIDER_PASSWORD }}'}
  when: V4_CFG_MULTITENANT_ENABLE
  tags:
    - install

- name: copy - create-cas-server script
  template:
    src: "{{ DEPLOY_DIR }}/sas-bases/examples/cas/create/create-cas-server.sh"
    dest: "{{ DEPLOY_DIR }}/multi-tenant"
    mode: "0770"
  when: V4_CFG_MULTITENANT_ENABLE
  tags:
    - install

# Preparing cas servers
- name: Create cas servers for tenants
  command:
  #$deploy/sas-bases/examples/cas/create/create-cas-server.sh --tenant acme --output ../multi-tenant/ --workers 2 --backup 1
    cmd: "{{ DEPLOY_DIR }}/multi-tenant/create-cas-server.sh --tenant {{ item }} --output {{ DEPLOY_DIR }}/multi-tenant --workers {{ CAS_WORKER_COUNT }} --backup {{ BACKUP }}"
  with_items: "{{ SAS_TENANT_IDS.split(',') }}"
  when: V4_CFG_MULTITENANT_ENABLE
  tags:
    - install
