- hosts: localhost
  tasks:
    - name: global tmp dir
      tempfile:
        state: directory
      register: tmpdir
      tags:
        - install
        - uninstall
        - update
        - onboard
        - offboard
    - name: common role
      include_role: 
        name: common
        public: yes
      tags:
        - install
        - uninstall
        - update
        - onboard
        - offboard
    - name: jump-server role
      include_role:
        name: jump-server
      when:
        - JUMP_SVR_HOST is defined
        - JUMP_SVR_USER is defined
        - JUMP_SVR_PRIVATE_KEY is defined
        - V4_CFG_MANAGE_STORAGE is defined
        - V4_CFG_MANAGE_STORAGE
      tags:
        - viya
    - name: baseline role
      include_role:
        name: baseline
      tags:
        - baseline
    - name: monitoring role - cluster
      include_role:
        name: monitoring
      tags:
        - cluster-monitoring
        - cluster-logging
    - name: vdm role
      include_role:
        name: vdm
      tags:
        - viya
    - name: multi-tenant role - setup
      include_role:
        name: multi-tenant
        tasks_from: multi_tenant_setup
      tags:
        - onboard
        - offboard
    - name: multi-tenant role - onboard offboard
      include_role:
        name: multi-tenant
        tasks_from: multi_tenant_onboard_offboard
      tags:
        - onboard
        - offboard
    - name: multi-tenant role - cas
      include_role:
        name: multi-tenant
        tasks_from: onboard_offboard_cas_servers
      tags:
        - onboard
        - offboard
    - name: monitoring role - namespace
      include_role:
        name: monitoring
        tasks_from: viya-monitoring
      tags:
        - viya-monitoring
    - name: Delete tmpdir
      file:
        path: "{{ tmpdir.path }}"
        state: absent
      tags:
        - install
        - uninstall
        - update
