---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: sas-ingress-certificate
files:
  - tls.crt={{ DEPLOY_DIR }}/{{ VDM_DIR }}/security/sas-nginx-ingress.crt
  - tls.key={{ DEPLOY_DIR }}/{{ VDM_DIR }}/security/sas-nginx-ingress.key
type: "kubernetes.io/tls"