apiVersion: builtin
kind: SecretGenerator
metadata:
  name: sas-consul-config
behavior: merge
files:
  - SITEDEFAULT_CONF=site-config/sitedefault.yaml
{% if V4_CFG_MULTITENANT_ENABLE == true %}
  - SASDEFAULT_CONF=site-config/multi-tenant/sasdefault.yaml
{% endif %}
