prometheus:
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    enabled: true
    tls:
    - hosts:
      - {{ V4M_PROMETHEUS_FQDN }}
      secretName: prometheus-ingress-tls-secret
    hosts:
    - {{ V4M_PROMETHEUS_FQDN }}
  prometheusSpec:
    externalUrl: "https://{{ V4M_PROMETHEUS_FQDN }}"

alertmanager:
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    enabled: true
    tls:
    - hosts:
      - {{ V4M_ALERTMANAGER_FQDN }}
      secretName: alertmanager-ingress-tls-secret
    hosts:
    - {{ V4M_ALERTMANAGER_FQDN  }}
  alertManagerSpec:
    externalUrl: "https://{{ V4M_ALERTMANAGER_FQDN }}"

grafana:
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    enabled: true
    tls:
    - hosts:
      - {{ V4M_GRAFANA_FQDN }}
      secretName: grafana-ingress-tls-secret
    hosts:
    - {{ V4M_GRAFANA_FQDN }}
